version: '1.0'
services:
    db:
        image: mysql:latest
        container_name: mysql-dev01
        ports:
            - "3036:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: developer
            MYSQL_PASSWORD: developer
        volumes:
            - ./db/:/docker-entrypoint-initdb.d/
            - ./settings:/etc/mysql/conf.d
    adminer:
        image: adminer
        restart: always
        ports:
          - 8080:8080
